package simpledb.execution;

import simpledb.storage.Field;
import simpledb.transaction.TransactionAbortedException;
import simpledb.common.DbException;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate p;
    private OpIterator child1;
    private OpIterator child2;
    private TupleDesc td1;
    private TupleDesc td2;
    private Tuple t1;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        this.td1 = child1.getTupleDesc();
        this.td2 = child2.getTupleDesc();
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return td1.getFieldName(p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return td2.getFieldName(p.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(td1, td2);
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        super.open();
        child1.open();
        child2.open();
        if (child1.hasNext()) {
            t1 = child1.next();
        }
    }

    public void close() {
        // some code goes here
        super.close();
        child1.close();
        child2.close();
        t1 = null;
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        child1.rewind();
        child2.rewind();
        if (child1.hasNext()) {
            t1 = child1.next();
        }
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        return nestedLoopJoin();
    }

    /**
     * 嵌套循环链接表，并返回符合连接条件的tuple
     *
     * @return 符合连接条件的tuple
     * @throws TransactionAbortedException
     * @throws DbException
     */
    private Tuple nestedLoopJoin() throws TransactionAbortedException, DbException {
        while (true) {
            while (child2.hasNext()) {
                Tuple t2 = child2.next();
                if (p.filter(t1, t2)) {
                    return merge(t1, t2);
                }
            }
            child2.rewind();
            if (!child1.hasNext()) {
                break;
            }
            t1 = child1.next();
        }
        return null;
    }

    /**
     * 合并两个tuple
     * 加入t1为(1, 5, 9), t2为(1, 3, 5)，则合并的tuple为(1, 5, 9, 1, 3, 5)
     *
     * @param t1 第一个tuple
     * @param t2 第二哥tuple
     * @return 合并的tuple
     */
    public Tuple merge(Tuple t1, Tuple t2) {
        Tuple mergeTuple = new Tuple(getTupleDesc());
        for (int i = 0; i < td1.numFields() + td2.numFields(); i++) {
            if (i < td1.numFields()) {
                mergeTuple.setField(i, t1.getField(i));
            } else {
                mergeTuple.setField(i, t2.getField(i - td1.numFields()));
            }
        }
        return mergeTuple;
    }

    @Override
    public OpIterator[] getChildren() {
        // some code goes here
        return new OpIterator[]{child1, child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // some code goes here
        if (this.child1 != children[0]) {
            this.child1 = children[0];
        }
        if (this.child2 != children[1]) {
            this.child2 = children[1];
        }
    }

}
